name: news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluent_ui: ^3.12.0
  window_manager: ^0.2.1
  transparent_image: ^2.0.0
  timeago: ^3.2.2
  http: ^0.13.4
  url_launcher: ^6.0.20
  share_plus: ^4.0.4
  clipboard: ^0.1.3
  macos_ui: ^1.7.1
  flutter_launcher_icons: ^0.10.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/name.webp"
  adaptive_icon_background: "images/name.webp"
  adaptive_icon_foreground: "images/name.webp"
